### ISSUE TITLE
Why the compiled folder?

### ISSUE THREAD

**Issue by thheller** [minimal-xyz/minimal-shadow-cljs#1]
Just curious why you don't use the default `node_modules/shadow-cljs` folder?

Is it just because some JS tools ignore the `/node_modules/` when watching? Or since `yarn` may delete the directory?

I added a quick fix for `create-react-app` which ignores `/node_modules` here:
https://github.com/thheller/shadow-cljs-examples/tree/master/cljs-react-app

It is of course not a problem, I'm just trying to understand if I should maybe change the default?

**Comment by jiyinyiyong** [comment]
For the most part it's out of habit. When I was using CoffeeScript in the old days, we use `src/` for source code and `lib/` for compiled JavaScript code, and even code in `lib/` is readable. So adding folder makes me feel safe.

Later in Webpack, the compiled JavaScript code just lives in memory. I think it's the most natural way. However, ClojureScript has a heavy compiler, unlike other compiled-to-js languages, which makes it unworthy to be built into a Webpack loader.

Yarn deleting assets is really bothering. Plus I would frequently check the compiled results there, and removing compiled files before switching `:dev`/`:release`. I think it fits my front-end workflow better.

**Comment by thheller** [comment]
Thanks for clarifying.
